modLoader = "kotlinforforge"
loaderVersion = "[1,)"
license = "GNU General Public License v3.0"

issueTrackerURL = "https://github.com/${repo}/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://modrinth.com/mod/${slug}"
authors = "btwonion"
description = '''
${description}
'''
logoFile = "${icon}"

[[mixins]]
config = "${mixins}"

[[dependencies.${id}]]
modId = "minecraft"
versionRange = "${mc}"
ordering = "NONE"
side = "CLIENT"